// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuantityMeasurementRepository.Data;

#nullable disable

namespace QuantityMeasurementApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.2.25163.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuantityMeasurementModel.Entities.MeasurementRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("BoolResult")
                        .HasColumnType("bit");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasError")
                        .HasColumnType("bit");

                    b.Property<string>("Operand1Category")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Operand1Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Operand1Value")
                        .HasColumnType("float");

                    b.Property<string>("Operand2Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Operand2Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Operand2Value")
                        .HasColumnType("float");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ResultCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("ResultValue")
                        .HasColumnType("float");

                    b.Property<double?>("ScalarResult")
                        .HasColumnType("float");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    // FIX: UserId was missing from snapshot — caused EF model/DB mismatch
                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Operand1Category");
                    b.HasIndex("Operation");
                    b.HasIndex("Timestamp");
                    b.HasIndex("UserId");  // added by AddUserIdToMeasurements migration

                    b.ToTable("quantity_measurements_ef", (string)null);
                });

            modelBuilder.Entity("QuantityMeasurementModel.Entities.MeasurementRecord", b =>
                {
                    b.HasOne("QuantityMeasurementModel.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired(false);
                });

            modelBuilder.Entity("QuantityMeasurementModel.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email").IsUnique();
                    b.HasIndex("Username").IsUnique();

                    b.ToTable("users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}